# Generated by Django 6.1 on 2026-08-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('hardware_version', models.CharField(max_length=50)),
                ('software_version', models.CharField(max_length=50)),
                ('last_beat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Device Details',
                'verbose_name_plural': 'Device Details',
            },
        ),
    ]
