# Generated by Django 6.1 on 2026-08-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device Details', 'verbose_name_plural': 'Device Details'},
        ),
    ]
