# Generated by Django 6.1 on 2026-08-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0002_alter_device_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_beat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
