# Generated by Django 6.1 on 2026-08-14 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0001_initial'),
        ('mqttapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqttmessage',
            name='received_at',
        ),
        migrations.AddField(
            model_name='mqttmessage',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_messages', to='deviceapp.device'),
        ),
        migrations.AlterField(
            model_name='mqttmessage',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
