# Generated by Django 6.1 on 2026-08-14 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0001_initial'),
        ('mqttapp', '0002_remove_mqttmessage_received_at_mqttmessage_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttmessage',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mqtt_messages', to='deviceapp.device'),
        ),
    ]
