# Generated by Django 6.1 on 2026-08-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0001_initial'),
        ('mqttapp', '0004_mqttmessage_received_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttmessage',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mqttmessage',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deviceapp.device'),
        ),
    ]
