# Generated by Django 6.1 on 2026-08-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttapp', '0005_mqttmessage_timestamp_alter_mqttmessage_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
