# Generated by Django 6.1 on 2026-08-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqttapp', '0006_alter_mqttmessage_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mqttmessage',
            options={'verbose_name': 'Logs', 'verbose_name_plural': 'Logs'},
        ),
    ]
