# Generated by Django 6.1 on 2026-08-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttapp', '0007_alter_mqttmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttmessage',
            name='device_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
