# Generated by Django 6.1 on 2026-08-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttapp', '0008_mqttmessage_device_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttmessage',
            name='send_receive',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
