# Generated by Django 6.1 on 2026-08-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttapp', '0009_mqttmessage_send_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttmessage',
            name='send_receive',
            field=models.CharField(blank=True, choices=[('send', 'Send'), ('receive', 'Receive')], max_length=10, null=True),
        ),
    ]
