# Generated by Django 6.1 on 2026-08-19 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
