# Generated by Django 6.1 on 2026-08-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_log_device_id_alter_log_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
