# Generated by Django 6.1 on 2026-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alter_log_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Device Data', 'verbose_name_plural': 'Device Data'},
        ),
        migrations.AddField(
            model_name='log',
            name='device_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
