# Generated by Django 6.1 on 2026-08-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_log_options_log_device_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='send_receive',
            field=models.CharField(blank=True, choices=[('send', 'Send'), ('receive', 'Receive')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
