# Generated by Django 6.1 on 2026-08-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_log_send_receive_alter_log_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='send_receive',
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
