# Generated by Django 6.1 on 2026-08-20 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('message_type', models.CharField(blank=True, max_length=50, null=True)),
                ('message_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('message', models.TextField()),
                ('send_receive', models.CharField(blank=True, choices=[('send', 'Send'), ('receive', 'Receive')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Device Data',
                'verbose_name_plural': 'Device Data',
            },
        ),
    ]
