# Generated by Django 6.1 on 2026-08-20 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devicedetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('message_type', models.CharField(blank=True, max_length=50, null=True)),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('message', models.TextField()),
                ('send_receive', models.CharField(blank=True, choices=[('send', 'Send'), ('receive', 'Receive')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devicedetails.device')),
            ],
            options={
                'verbose_name': 'devicedata',
                'verbose_name_plural': 'devicedata',
            },
        ),
    ]
